NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src

#DIRS	 := /home/wuxy/ysyx-workbench/am-kernels/tests/cpu-tests
#SRCS 	 += $(shell find -L $(DIRS) -name "*.c")
include $(AM_HOME)/Makefile
